from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^$', views.home, name='home'),
    url(r'^index_cn/$', views.indexcn, name='indexcn'),
    url(r'^calendar/$', views.calendar, name='calendar'),
    url(r'^chartjs/$', views.chartjs, name='chartjs'),
    url(r'^chartjs2/$', views.chartjs2, name='chartjs2'),
    url(r'^contacts/$', views.contacts, name='contacts'),
    url(r'^ecommerce/$', views.ecommerce, name='ecommerce'),
    url(r'^echarts/$', views.echarts, name='echarts'),
    url(r'^fixedfooter/$', views.fixedfooter, name='fixedfooter'),
    url(r'^fixedsidebar/$', views.fixedsidebar, name='fixedsidebar'),
    url(r'^form/$', views.form, name='form'),
    url(r'^formadvanced/$', views.formadvanced, name='formadvanced'),
    url(r'^formbuttons/$', views.formbuttons, name='formbuttons'),
    url(r'^formupload/$', views.formupload, name='formupload'),
    url(r'^formvalidation/$', views.formvalidation, name='formvalidation'),
    url(r'^formwizards/$', views.formwizards, name='formwizards'),
    url(r'^generalelements/$', views.generalelements, name='generalelements'),
    url(r'^glyphicons/$', views.glyphicons, name='glyphicons'),
    url(r'^icons/$', views.icons, name='icons'),
    url(r'^inbox/$',views.inbox,name='inbox'),
    url(r'^index2/$',views.index2,name='index2'),
    url(r'^index3/$', views.index3, name='index3'),
    url(r'^invoice/$', views.invoice, name='invoice'),
    url(r'^tables/$', views.tables, name='tables'),
    url(r'^tables_dynamic/$', views.tabledynamic, name='tabledynamic'),
    url(r'^media_gallery/$', views.mediagallery, name='mediagallery'),
    url(r'^typography/$', views.typography, name='typography'),
    url(r'^widgets/$', views.widgets, name='widgets'),
    url(r'^403error/$', views.error403, name='403error'),
    url(r'^404error/$', views.error404, name='404error'),
    url(r'^500error/$', views.error500, name='500error'),
    url(r'^plainpage/$', views.plainpage, name='plainpage'),
    url(r'^login/$', views.login, name='loginpage'),
    url(r'^pricingtables/$', views.pricingtables, name='pricingtables'),
    url(r'^othercharts/$', views.othercharts, name='othercharts'),
    url(r'^morisjs/$', views.morisjs, name='morisjs'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^projects/$', views.projects, name='projects'),
    url(r'^projectsdetails/$', views.projectdetail, name='projectdetail'),
    url(r'^level2/$', views.level2, name='level2'),



]